spring:
  application:
    name: microservicio-gateway
  cloud:
    gateway:
      routes:
        - id: microservicio-oauth2
          uri: lb://microservicio-oauth2
          predicates:
            - Path=/oauth2/**
          filters:
            - RewritePath=/oauth2/(?<path>.*), /auth/oauth2/$\{path}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:https://hc-back-clinico-production.up.railway.app/eureka}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    healthcheck:
      enabled: false  # ← DESHABILITAR HEALTHCHECK ESTRICTO
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# TOLERANCIA A FALLOS RIBBON
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1