spring:
  application:
    name: microservicio-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: https://spring-cloud-netflix-eureka-production-5bb2.up.railway.app/eureka