spring:
  application:
    name: microservicio-usuarios
  datasource:
    url: jdbc:postgresql://switchback.proxy.rlwy.net:43095/railway
    username: postgres
    password: QzlJMZtbYmqOxVSspnQAICcTDjkgOqMG
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8002

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      hibernate:
        SQL: debug